version: "3.9"

services:
  db:
    image: postgres:16
    container_name: idempotent-api-challenge-db
    restart: always
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: idempotent_api_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: